-- PostgreSQL quiz database

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;
SET default_tablespace = '';
SET default_table_access_method = heap;

-- create DB user

CREATE USER quizuser WITH ENCRYPTED PASSWORD 'quizpass';
GRANT ALL PRIVILEGES ON DATABASE quiz TO quizuser;

-- question table

CREATE TABLE IF NOT EXISTS public.question (
  id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  text character varying(1000) NOT NULL UNIQUE
);

COMMENT ON TABLE public.question IS 'question text';
COMMENT ON COLUMN public.question.id IS 'unique question ID';
COMMENT ON COLUMN public.question.text IS 'unique question text';

ALTER TABLE public.question OWNER TO quizuser;

-- answer table

CREATE TABLE IF NOT EXISTS public.answer (
  id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question_id smallint NOT NULL,
  text character varying(500) NOT NULL,
  correct boolean DEFAULT false NOT NULL,
  CONSTRAINT answer_quesion_fk FOREIGN KEY (question_id) REFERENCES public.question(id) ON UPDATE CASCADE ON DELETE CASCADE
);

COMMENT ON TABLE public.answer IS 'individual question answers';
COMMENT ON COLUMN public.answer.id IS 'unique answer ID';
COMMENT ON COLUMN public.answer.question_id IS 'question ID';
COMMENT ON COLUMN public.answer.text IS 'answer text';
COMMENT ON COLUMN public.answer.correct IS 'answer is correct';

ALTER TABLE public.answer OWNER TO quizuser;
